In [1]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import StandardScaler

In [2]:
n = 2
target_market = ["GBPUSD","USDCAD","XAUUSD"]
df = pd.read_csv("Generated"+target_market[n] +" dbot.csv")


In [3]:
print(len(df))

29592


In [4]:
df.head()

Time   Open  Close  Tick Volume
0  1086926400  384.0  383.8           47
1  1086940800  383.8  383.6          170
2  1086955200  383.5  384.6           57
3  1086969600  384.3  384.1           29
4  1087171200  384.3  382.6          135

In [5]:
# Change the position of the 'B' column
df = df[['Time', 'Open', 'Tick Volume', 'Close']]
df.tail()

Time     Open  Tick Volume    Close
29587  1697227200  1927.19        21549  1929.60
29588  1697414400  1927.12        12449  1921.70
29589  1697428800  1921.70        13683  1920.14
29590  1697443200  1920.16        32883  1911.63
29591  1697457600  1911.61        33853  1917.48

In [6]:
x = df.values
y = x[:,-1]
x = x[:,:3]

print(x)
print(y)

[[1.0869264e+09 3.8400000e+02 4.7000000e+01]
 [1.0869408e+09 3.8380000e+02 1.7000000e+02]
 [1.0869552e+09 3.8350000e+02 5.7000000e+01]
 ...
 [1.6974288e+09 1.9217000e+03 1.3683000e+04]
 [1.6974432e+09 1.9201600e+03 3.2883000e+04]
 [1.6974576e+09 1.9116100e+03 3.3853000e+04]]
[ 383.8   383.6   384.6  ... 1920.14 1911.63 1917.48]


In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.0015, random_state=0)
sc_x = StandardScaler()
sc_y = StandardScaler()

x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train.reshape((len(y_train),1)))
y_train = y_train.reshape(-1)

x_test = sc_x.transform(x_test)

print(x_test.shape)



(45, 3)


In [8]:
regressor = RandomForestRegressor(n_estimators=300)
regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300)

In [9]:
import joblib

joblib.dump(sc_x,target_market[n]+' sc_x.joblib')
joblib.dump(sc_y,target_market[n]+' sc_y.joblib')
joblib.dump(regressor,target_market[n]+' regressor.joblib')

['XAUUSD regressor.joblib']

In [10]:
score = regressor.score(
    x_test,
    sc_y.transform(y_test.reshape((len(y_test),1))).reshape(-1)
)
print(score)

0.9997665556780402
