In [1]:
import numpy as np
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import StandardScaler

In [2]:
n = 0

In [3]:

target_market =  ["GBPUSD","USDCAD","XAUUSD","AUDUSD","USDJPY","NZDUSD","EURUSD","EURJPY"]
df = pd.read_csv("Generated"+target_market[n] +" dbot.csv")


In [4]:
print(len(df))

40334


In [5]:
df.head()

Time    Open   Close  Tick Volume
0  737164800  1.5370  1.5338         2781
1  737251200  1.5328  1.5225         2571
2  737337600  1.5228  1.5387         2711
3  737596800  1.5365  1.5355         2921
4  737683200  1.5350  1.5365         2711

In [6]:
# Change the position of the 'B' column
df = df[['Open', 'Tick Volume', 'Close']]
df.tail()

Open  Tick Volume    Close
40329  1.25448        16460  1.25470
40330  1.25345        14583  1.25455
40331  1.25454        10930  1.25414
40332  1.25414        24130  1.25534
40333  1.25534        11925  1.25852

In [7]:
x = df.values
y = x[:,-1]
x = x[:,:2]

print(x)
print(y)

[[1.53700e+00 2.78100e+03]
 [1.53280e+00 2.57100e+03]
 [1.52280e+00 2.71100e+03]
 ...
 [1.25454e+00 1.09300e+04]
 [1.25414e+00 2.41300e+04]
 [1.25534e+00 1.19250e+04]]
[1.5338  1.5225  1.5387  ... 1.25414 1.25534 1.25852]


In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.01, random_state=0)
sc_x = StandardScaler()
sc_y = StandardScaler()

x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train.reshape((len(y_train),1)))
y_train = y_train.reshape(-1)

x_test = sc_x.transform(x_test)

print(x_test)



[[-1.57271594e+00  8.74573140e-01]
 [-1.95600317e+00  4.71822123e-02]
 [ 6.44481221e-01 -4.45830439e-01]
 [-2.61160805e-01 -2.02294069e-01]
 [-1.24643663e+00  2.58694712e-01]
 [-1.16195109e+00  6.30455692e-01]
 [-7.59956691e-01  1.00266862e+00]
 [ 1.95193104e+00 -6.47593736e-01]
 [-8.39497187e-01 -1.30434053e-01]
 [ 2.59314029e-02 -8.63366671e-02]
 [ 3.19601446e-01  9.27193008e-01]
 [-1.62253955e+00  7.05382430e+00]
 [-5.43914440e-01 -6.21380648e-01]
 [-1.36856978e+00  6.14250064e-01]
 [ 9.55925417e-01 -5.48939554e-01]
 [ 2.14646704e+00 -4.93737116e-01]
 [-1.39558089e+00 -2.25278944e-01]
 [ 3.76982567e-01 -6.66317370e-01]
 [ 2.73416642e-01 -6.48174814e-01]
 [-6.69047188e-02  4.75695978e-02]
 [-4.87979510e-01 -1.31273389e-01]
 [-1.51682767e+00 -3.86495889e-01]
 [ 2.31581132e+00 -6.42170339e-01]
 [-1.21066898e-01  1.12714931e-01]
 [ 3.00474406e-01 -6.87817267e-01]
 [-1.35686030e+00  6.03390276e+00]
 [ 4.38921602e-02 -5.58107678e-01]
 [-1.33642702e+00  3.57800843e-01]
 [ 4.57582129e-02 -5

In [10]:
regressor = RandomForestRegressor(n_estimators=300)
regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300)

In [11]:

joblib.dump(sc_x,target_market[n]+' sc_x.joblib')
joblib.dump(sc_y,target_market[n]+' sc_y.joblib')
joblib.dump(regressor,target_market[n]+' regressor.joblib')

['GBPUSD regressor.joblib']

In [12]:
score = regressor.score(
    x_test,
    sc_y.transform(y_test.reshape((len(y_test),1))).reshape(-1)
)
print(score)
n+=1
print(n)

0.997724849411636
1
