In [82]:
import numpy as np
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import StandardScaler

In [116]:
n = 0

In [126]:

target_market =  ["GBPUSD","USDCAD","XAUUSD","AUDUSD","USDJPY","NZDUSD","EURUSD","EURJPY"]
df = pd.read_csv("Generated"+target_market[n] +" dbot.csv")


In [127]:
print(len(df))

40218


In [128]:
df.head()

Time    Open    High     Low   Close  Tick Volume
0  735955200  1.2760  1.2810  1.2683  1.2690         1841
1  736041600  1.2715  1.2740  1.2687  1.2715         1061
2  736128000  1.2715  1.2750  1.2693  1.2711         1101
3  736387200  1.2695  1.2705  1.2670  1.2675          501
4  736473600  1.2668  1.2732  1.2658  1.2710         1061

In [129]:
# Change the position of the 'B' column
df = df[['Time', 'Open',"High", "Low", 'Tick Volume', 'Close']]
df.tail()

Time     Open     High      Low  Tick Volume    Close
40213  1700006400  1.36833  1.37094  1.36801         6224  1.37026
40214  1700020800  1.37025  1.37025  1.36805         4638  1.36878
40215  1700035200  1.36878  1.37038  1.36763        12147  1.36969
40216  1700049600  1.36970  1.37005  1.36590        18158  1.36814
40217  1700064000  1.36815  1.36949  1.36691        10791  1.36844

In [130]:
x = df.values
y = x[:,-1]
x = x[:,:5]

print(x)
print(y)

[[7.3595520e+08 1.2760000e+00 1.2810000e+00 1.2683000e+00 1.8410000e+03]
 [7.3604160e+08 1.2715000e+00 1.2740000e+00 1.2687000e+00 1.0610000e+03]
 [7.3612800e+08 1.2715000e+00 1.2750000e+00 1.2693000e+00 1.1010000e+03]
 ...
 [1.7000352e+09 1.3687800e+00 1.3703800e+00 1.3676300e+00 1.2147000e+04]
 [1.7000496e+09 1.3697000e+00 1.3700500e+00 1.3659000e+00 1.8158000e+04]
 [1.7000640e+09 1.3681500e+00 1.3694900e+00 1.3669100e+00 1.0791000e+04]]
[1.269   1.2715  1.2711  ... 1.36969 1.36814 1.36844]


In [131]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.002, random_state=0)
sc_x = StandardScaler()
sc_y = StandardScaler()

x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train.reshape((len(y_train),1)))
y_train = y_train.reshape(-1)

x_test = sc_x.transform(x_test)

print(x_test.shape)



(81, 5)


In [123]:
regressor = RandomForestRegressor(n_estimators=300)
regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300)

In [124]:

joblib.dump(sc_x,target_market[n]+' sc_x.joblib')
joblib.dump(sc_y,target_market[n]+' sc_y.joblib')
joblib.dump(regressor,target_market[n]+' regressor.joblib')

['GBPUSD regressor.joblib']

In [125]:
score = regressor.score(
    x_test,
    sc_y.transform(y_test.reshape((len(y_test),1))).reshape(-1)
)
print(score)
n+=1
print(n)

0.9999065271206169
