In [1]:
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import numpy as np
import MetaTrader5 as mt5

In [2]:
if mt5.initialize():
    print("MetaTrader5 initialized")
else:
    print("MetaTrader5 not initialized")

MetaTrader5 initialized


In [3]:
print(mt5.account_info())
print("\n")
print(mt5.terminal_info())

AccountInfo(login=31501023, trade_mode=0, leverage=500, limit_orders=50, margin_so_mode=0, trade_allowed=True, trade_expert=True, margin_mode=2, currency_digits=2, fifo_close=False, balance=9988.64, credit=0.0, profit=0.0, equity=9988.64, margin=0.0, margin_free=9988.64, margin_level=0.0, margin_so_call=100.0, margin_so_so=50.0, margin_initial=0.0, margin_maintenance=0.0, assets=0.0, liabilities=0.0, commission_blocked=0.0, name='Demo Derived', server='Deriv-Demo', currency='USD', company='Deriv.com Limited')


TerminalInfo(community_account=False, community_connection=False, connected=True, dlls_allowed=False, trade_allowed=True, tradeapi_disabled=False, email_enabled=False, ftp_enabled=False, notifications_enabled=False, mqid=False, build=4294, maxbars=100000, codepage=0, ping_last=168583, community_balance=0.0, retransmission=0.0, company='MetaQuotes Software Corp.', name='MetaTrader 5', language='English', path='C:\\Program Files\\MetaTrader 5', data_path='C:\\Users\\omage\\AppData

In [4]:
sc_x = joblib.load("v75i sc_x.joblib")
sc_y = joblib.load("v75i sc_y.joblib")
model = joblib.load("v75i t_model.joblib")

In [5]:
rates = mt5.copy_rates_from_pos("Volatility 75 Index", mt5.TIMEFRAME_M30, 0, 100)

In [6]:
x = []
y = []

i = 0
for rate in rates:
    if i == 0:
        i=1
    else:    
        x.append([rate[1],rate[2],rate[3],rate[4],rate[5]])
i = 0
for rate in rates:
    if i < len(rates) - 1:
        y.append(rate[4]) 
        i += 1
    else:
        print("done executing") 

done executing


In [7]:
x = np.array(x)
y = np.array(y)
x = sc_x.transform(x)
y = sc_y.transform(y.reshape((len(y),1)))

In [8]:
y = y.reshape(-1)

In [9]:
print(x)

[[ -1.3300733   -1.33167602  -1.32939249  -1.33049568   0.03360927]
 [ -1.33071186  -1.33336988  -1.33055958  -1.33249309   0.03360927]
 [ -1.33264379  -1.33362241  -1.33382416  -1.33559141   0.03360927]
 [ -1.33537691  -1.3361675   -1.33542009  -1.33752373   0.03360927]
 [ -1.33777155  -1.32933539  -1.33510774  -1.32651017  -0.05622067]
 [ -1.32657216  -1.32820664  -1.32636463  -1.32648659   0.03360927]
 [ -1.32646201  -1.32321661  -1.32461404  -1.32117791   0.03360927]
 [ -1.32115941  -1.31725208  -1.31871589  -1.31521474   0.03360927]
 [ -1.3152063   -1.3125648   -1.31260778  -1.31045134   0.03360927]
 [ -1.31039987  -1.31152288  -1.31251784  -1.31542814   0.03360927]
 [ -1.31531624  -1.31837432  -1.31619578  -1.31729079   0.03360927]
 [ -1.31730702  -1.31852007  -1.31840112  -1.3189509    0.03360927]
 [ -1.31897327  -1.32201456  -1.32169821  -1.32331766   0.03360927]
 [ -1.32326144  -1.32575151  -1.32410018  -1.3268951    0.03360927]
 [ -1.3268422   -1.32776323  -1.33084623  -1.333

In [10]:
print(model.score(x,y))

0.9995381513288567


[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 146 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.0s finished


In [11]:
market = "Volatility 75 Index"
lot = 0.01

In [12]:
rates = mt5.copy_rates_from_pos(market, mt5.TIMEFRAME_H1, 0, 2)
rates

array([(1716465600, 163243.26, 163268.9, 160758.74, 161173.08, 1800, 4279, 0),
       (1716469200, 161168.56, 161372. , 160437.84, 160612.56,  534, 4279, 0)],
      dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [13]:
x = []
for rate in rates:      
    x.append([rate[1],rate[2],rate[3],rate[4],rate[5]])
print(x)

[[163243.26, 163268.9, 160758.74, 161173.08, 1800], [161168.56, 161372.0, 160437.84, 160612.56, 534]]


In [14]:
x = np.array(x)
x = sc_x.transform(x)

In [15]:
print(x)

[[ -1.34175311  -1.34459119  -1.34899412  -1.35021616  80.8805531 ]
 [ -1.35022008  -1.35229863  -1.35030952  -1.35250369 -32.84414789]]


In [16]:
y_pred = model.predict(x)
print(y_pred)

[-1.34175115 -1.35008667]


[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 146 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.0s finished


In [17]:
y_pred = sc_y.inverse_transform(y_pred.reshape((len(y_pred),1)))

print(y_pred)

[[163243.5361 ]
 [161201.04505]]
