In [1]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import StandardScaler

In [21]:
df = pd.read_csv("GeneratedXAUUSD dbot.csv")


In [22]:
print(len(df))

29575


In [23]:
df.head()

Time   Open  Close  Tick Volume
0  1086926400  384.0  383.8           47
1  1086940800  383.8  383.6          170
2  1086955200  383.5  384.6           57
3  1086969600  384.3  384.1           29
4  1087171200  384.3  382.6          135

In [24]:
# Change the position of the 'B' column
df = df[['Time', 'Open', 'Tick Volume', 'Close']]
df.tail()

Time     Open  Tick Volume    Close
29570  1696982400  1860.27         6316  1860.99
29571  1696996800  1860.95        16156  1859.73
29572  1697011200  1859.73        35895  1869.56
29573  1697025600  1869.57        44375  1872.84
29574  1697040000  1872.88         3283  1873.28

In [25]:
x = df.values
y = x[:,-1]
x = x[:,:3]

print(x)
print(y)

[[1.0869264e+09 3.8400000e+02 4.7000000e+01]
 [1.0869408e+09 3.8380000e+02 1.7000000e+02]
 [1.0869552e+09 3.8350000e+02 5.7000000e+01]
 ...
 [1.6970112e+09 1.8597300e+03 3.5895000e+04]
 [1.6970256e+09 1.8695700e+03 4.4375000e+04]
 [1.6970400e+09 1.8728800e+03 3.2830000e+03]]
[ 383.8   383.6   384.6  ... 1869.56 1872.84 1873.28]


In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.0015, random_state=0)
sc_x = StandardScaler()
sc_y = StandardScaler()

x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train.reshape((len(y_train),1)))
y_train = y_train.reshape(-1)

x_test = sc_x.transform(x_test)

print(x_test.shape)



(45, 3)


In [27]:
regressor = RandomForestRegressor(n_estimators=300)
regressor.fit(x_train,y_train)


RandomForestRegressor(n_estimators=300)

In [28]:
import joblib

joblib.dump(sc_x,'XAUUSD sc_x.joblib')
joblib.dump(sc_y,'XAUUSD sc_y.joblib')
joblib.dump(regressor,'XAUUSD regressor.joblib')

['XAUUSD regressor.joblib']

In [29]:
score = regressor.score(
    x_test,
    sc_y.transform(y_test.reshape((len(y_test),1))).reshape(-1)
)
print(score)

0.9998299906440925
