<a href="https://colab.research.google.com/github/dbright123/Dbot-Advance/blob/main/lstm_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import MetaTrader5 as mt5
import numpy as np
import pandas as pd





In [ ]:
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)

trade_active = mt5.initialize()

print(trade_active)

if not trade_active:
    print('Initialization failed, check internet connection. You must have Meta Trader 5 installed.')
    mt5.shutdown()

else:
    print(mt5.account_info()._asdict())
    print("\n")
    print(mt5.terminal_info()._asdict())
    print("\n")
    print(mt5.symbols_total())

MetaTrader5 package author:  MetaQuotes Ltd.
MetaTrader5 package version:  5.0.5200
True
{'login': 213644473, 'trade_mode': 0, 'leverage': 1000, 'limit_orders': 500, 'margin_so_mode': 0, 'trade_allowed': True, 'trade_expert': True, 'margin_mode': 2, 'currency_digits': 2, 'fifo_close': False, 'balance': 200.0, 'credit': 0.0, 'profit': 0.0, 'equity': 200.0, 'margin': 0.0, 'margin_free': 200.0, 'margin_level': 0.0, 'margin_so_call': 25.0, 'margin_so_so': 15.0, 'margin_initial': 0.0, 'margin_maintenance': 0.0, 'assets': 0.0, 'liabilities': 0.0, 'commission_blocked': 0.0, 'name': 'micheal bright omage ', 'server': 'OctaFX-Demo', 'currency': 'USD', 'company': 'Octa Markets Incorporated'}


{'community_account': False, 'community_connection': False, 'connected': True, 'dlls_allowed': False, 'trade_allowed': False, 'tradeapi_disabled': False, 'email_enabled': False, 'ftp_enabled': False, 'notifications_enabled': False, 'mqid': False, 'build': 5327, 'maxbars': 100000, 'codepage': 0, 'ping_last'

In [ ]:
account = mt5.account_info()
terminal = mt5.terminal_info()

print(account.equity)

if(terminal.connected == True or terminal.trade_allowed == True):
    print("AI is successfully functional")
else:
    print("Please make sure metatrade 5 has internet and algo Trade is Turn On")

200.0
AI is successfully functional


In [ ]:
symbols = mt5.symbols_get()
print(len(symbols))
t_symbol = []
for symbol in symbols:
    if "USD" in symbol.name:
        print("Yes ", symbol.name)
        t_symbol.append(symbol.name)

print(len(t_symbol))

280
Yes  EURUSD
Yes  GBPUSD
Yes  USDJPY
Yes  USDCHF
Yes  AUDUSD
Yes  NZDUSD
Yes  USDCAD
Yes  USDMXN
Yes  USDZAR
Yes  XAGUSD
Yes  XAUUSD
Yes  XBRUSD
Yes  XTIUSD
Yes  XNGUSD
Yes  BTCUSD
Yes  ETHUSD
Yes  LTCUSD
Yes  XRPUSD
Yes  BCHUSD
Yes  AAVEUSD
Yes  ADAUSD
Yes  ALGOUSD
Yes  ATOMUSD
Yes  AVAXUSD
Yes  AXSUSD
Yes  BNBUSD
Yes  DASHUSD
Yes  DOGEUSD
Yes  DOTUSD
Yes  FILUSD
Yes  GRTUSD
Yes  ICPUSD
Yes  IOTAUSD
Yes  LINKUSD
Yes  LRCUSD
Yes  MANAUSD
Yes  NEARUSD
Yes  SOLUSD
Yes  UNIUSD
Yes  ZECUSD
Yes  ETCUSD
Yes  TRXUSD
Yes  FETUSD
Yes  ARBUSD
Yes  APTUSD
Yes  SUIUSD
Yes  USDDKK
Yes  USDCZK
Yes  USDHUF
Yes  USDNOK
Yes  USDPLN
Yes  USDSEK
Yes  USDSGD
Yes  USDHKD
Yes  USDCNH
Yes  USDTRY
Yes  XBRUSD.Daily
Yes  XTIUSD.Daily
Yes  BTCUSD.Daily
Yes  ETHUSD.Daily
Yes  XRPUSD.Daily
Yes  LTCUSD.Daily
Yes  BCHUSD.Daily
Yes  LINKUSD.Daily
Yes  SOLUSD.Daily
65


In [ ]:
market = mt5.copy_rates_from_pos(t_symbol[0], mt5.TIMEFRAME_H1, 0, 99999)
display(market)

array([(1251374400, 1.42654, 1.4275 , 1.42551, 1.42554, 2320, 20, 0),
       (1251378000, 1.4255 , 1.42816, 1.4254 , 1.42773, 2302, 20, 0),
       (1251381600, 1.42774, 1.42818, 1.42469, 1.4256 , 3678, 20, 0), ...,
       (1759525200, 1.17335, 1.17399, 1.17265, 1.17393, 2009,  8, 0),
       (1759528800, 1.1739 , 1.17418, 1.17369, 1.17405, 1529,  8, 0),
       (1759532400, 1.17408, 1.17444, 1.1738 , 1.1738 , 1423,  8, 0)],
      dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [ ]:
test_symbol = []
for t_s in t_symbol:
    market = mt5.copy_rates_from_pos(t_s, mt5.TIMEFRAME_H1, 0, 99999)
    if(len(market) > 80000):
        data = []
        for i in range(len(market)):
            data.append([market[i][1],market[i][2],market[i][3],market[i][4],market[i][5]])
        df = pd.DataFrame(data, columns=["open", "high","low", "close","tick_volume"])
        df.to_csv("Generated"+t_s+" dbot.csv", index=False)
        test_symbol.append(t_s)


In [ ]:

for t_s in test_symbol:
    market = mt5.copy_rates_from_pos(t_s, mt5.TIMEFRAME_D1, 0, 1000)
    if(len(market) > 900):
        data = []
        for i in range(len(market)):
            data.append([market[i][1],market[i][2],market[i][3],market[i][4],market[i][5]])
        df = pd.DataFrame(data, columns=["open", "high","low", "close","tick_volume"])
        df.to_csv("Generated"+t_s+" test.csv", index=False)



In [ ]:
import joblib

joblib.dump(t_symbol,"symbol.joblib")

['symbol.joblib']

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf


In [2]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
import math
import joblib
import os
from sklearn.model_selection import train_test_split

In [3]:
from tensorflow.keras.optimizers import SGD,Adam
import matplotlib.pyplot as plt

from tensorflow.keras.utils import plot_model

from tensorflow.keras import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, BatchNormalization, LayerNormalization, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

from sklearn.metrics import r2_score
from tensorflow.keras.models import load_model

In [24]:
# Get the list of all files and directories in the specified path

dir_contents = os.listdir(".")
t_symbol = joblib.load("symbol.joblib")

In [ ]:
print(t_symbol)

['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD', 'NZDUSD', 'USDCAD', 'USDMXN', 'USDZAR', 'XAGUSD', 'XAUUSD', 'XBRUSD', 'XTIUSD', 'XNGUSD', 'BTCUSD', 'ETHUSD', 'LTCUSD', 'XRPUSD', 'BCHUSD', 'AAVEUSD', 'ADAUSD', 'ALGOUSD', 'ATOMUSD', 'AVAXUSD', 'AXSUSD', 'BNBUSD', 'DASHUSD', 'DOGEUSD', 'DOTUSD', 'FILUSD', 'GRTUSD', 'ICPUSD', 'IOTAUSD', 'LINKUSD', 'LRCUSD', 'MANAUSD', 'NEARUSD', 'SOLUSD', 'UNIUSD', 'ZECUSD', 'ETCUSD', 'TRXUSD', 'FETUSD', 'ARBUSD', 'APTUSD', 'SUIUSD', 'USDDKK', 'USDCZK', 'USDHUF', 'USDNOK', 'USDPLN', 'USDSEK', 'USDSGD', 'USDHKD', 'USDCNH', 'USDTRY', 'XBRUSD.Daily', 'XTIUSD.Daily', 'BTCUSD.Daily', 'ETHUSD.Daily', 'XRPUSD.Daily', 'LTCUSD.Daily', 'BCHUSD.Daily', 'LINKUSD.Daily', 'SOLUSD.Daily']


In [ ]:
#t_symbol = ["EURUSD","AUDUSD","GBPUSD","USDCAD"]

In [25]:

# Filter the list to include only files, not directories
# os.path.join is used to create a full path for isfile() to check
files = [item for item in dir_contents]

file_target = []
test_target = []

for filename in files:
    for t_s in t_symbol:
        if t_s in filename  and "dbot.csv" in filename:
            print(filename)
            file_target.append(filename)
            test_target.append(filename.replace("dbot","test"))

print("----------------------------------------------------")

print(len(file_target))
print(len(test_target))
train_dfs = []
for f_t in file_target:
    train_dfs.append(pd.read_csv(f_t))

train_dfs_test = []
for f_t in test_target:
    train_dfs_test.append(pd.read_csv(f_t))

GeneratedEURUSD dbot.csv
GeneratedGBPUSD dbot.csv
----------------------------------------------------
2
2


In [26]:
display(train_dfs[0])

open     high      low    close
0      1.42713  1.42787  1.42610  1.42664
1      1.42665  1.42774  1.42571  1.42749
2      1.42748  1.44049  1.42742  1.43697
3      1.43698  1.43764  1.43510  1.43574
4      1.43572  1.43631  1.43407  1.43407
...        ...      ...      ...      ...
99994  1.17272  1.17283  1.17154  1.17158
99995  1.17159  1.17162  1.17059  1.17114
99996  1.17119  1.17187  1.17093  1.17158
99997  1.17162  1.17245  1.17098  1.17237
99998  1.17237  1.17277  1.17234  1.17273

[99999 rows x 4 columns]

In [27]:
display(train_dfs_test[0])

open     high      low    close
0    1.12383  1.13035  1.12343  1.12734
1    1.12815  1.13025  1.12605  1.12783
2    1.12826  1.13419  1.12640  1.13249
3    1.13230  1.13418  1.12899  1.13272
4    1.13209  1.13433  1.13034  1.13140
..       ...      ...      ...      ...
995  1.17242  1.17621  1.17117  1.17318
996  1.17321  1.17783  1.17147  1.17274
997  1.17272  1.17581  1.16825  1.17136
998  1.17132  1.17592  1.17103  1.17380
999  1.17328  1.17328  1.17059  1.17272

[1000 rows x 4 columns]

In [28]:
print(train_dfs[0].values)

[[1.42713 1.42787 1.4261  1.42664]
 [1.42665 1.42774 1.42571 1.42749]
 [1.42748 1.44049 1.42742 1.43697]
 ...
 [1.17119 1.17187 1.17093 1.17158]
 [1.17162 1.17245 1.17098 1.17237]
 [1.17237 1.17277 1.17234 1.17273]]


In [29]:
def create_sequences(data_scaled, seq_len, pred_steps = 10 ):
    """
    data_scaled: np.array shaped (n_rows, n_features)
    returns X (n_samples, seq_len, n_features), y (n_samples, n_features)
    where y is the row immediately following the window.
    """
    X, y = [], []
    n_rows = data_scaled.shape[0]
    for i in range(n_rows - seq_len - pred_steps + 1):
        X.append(data_scaled[i:i+seq_len])
        y.append(data_scaled[i+seq_len:i+seq_len+pred_steps,2:-1])
    X = np.array(X)
    y = np.array(y)
    return X, y





In [30]:
n = 0

In [31]:

m_label = file_target[n].replace("dbot.csv","")
train_df = train_dfs[n]
train_df_test = train_dfs_test[n]
print(m_label)
SEQ_LEN = 240 # length of input sequence (timesteps). Typical choices: 30, 60, 90
n_rows, n_features = train_df.values.shape
scaler = MinMaxScaler(feature_range=(0, 1))
#scaler = StandardScaler()
#s = scaler.fit_transform(train_df.values)
#s1 = scaler.transform(train_df_test.values)

X, y = create_sequences(train_df.values, SEQ_LEN, 20)  # X: (n_samples, SEQ_LEN, n_features), y: (n_samples, n_features)
X1, y1 = create_sequences(train_df_test.values, SEQ_LEN, 20)  # X: (n_samples, SEQ_LEN, n_features), y: (n_samples, n_features)
#X = scaler.fit_transform(X,y)
#X1 = scaler.transform(X1,y1)
n_samples = X.shape[0]

#joblib.dump(scaler, m_label + ' scaler.joblib')





GeneratedEURUSD 


In [32]:
print(X.shape)

(99755, 240, 4)


In [33]:
print(y)

[[[1.4582 ]
  [1.4568 ]
  [1.458  ]
  [1.4574 ]
  [1.4576 ]]

 [[1.4568 ]
  [1.458  ]
  [1.4574 ]
  [1.4576 ]
  [1.4575 ]]

 [[1.458  ]
  [1.4574 ]
  [1.4576 ]
  [1.4575 ]
  [1.4571 ]]

 ...

 [[1.1738 ]
  [1.17259]
  [1.17154]
  [1.17059]
  [1.17093]]

 [[1.17259]
  [1.17154]
  [1.17059]
  [1.17093]
  [1.17098]]

 [[1.17154]
  [1.17059]
  [1.17093]
  [1.17098]
  [1.17234]]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, shuffle=False)
X_val, X_test, y_val,  y_test = train_test_split(X_test, y_test, test_size=0.01, random_state=0, shuffle=False)

seq_len = X_train.shape[1]
n_features = X_train.shape[2]
output_dim = y_train.shape[2]

i = Input(shape=(seq_len, n_features))
X = Bidirectional(LSTM(200, return_sequences=True))(i)
X = Bidirectional(LSTM(200, return_sequences=True))(X)
X = Bidirectional(LSTM(200, return_sequences=True))(X)
X = Bidirectional(LSTM(200))(X)
#X = Dropout(0.5)(X)
X = Dense(150, activation="relu")(X)
X = Dropout(0.25)(X)
X = Dense(output_dim)(X)

model = Model(i, X)
model.summary()
try:
  # Create the visualization
  img_path = f"model_architecture.png"
  plot_model(
      model,
      to_file=img_path,
      show_shapes=True,
      show_layer_names=True,
      rankdir='TB',  # TB: top to bottom, LR: left to right
      dpi=96,
      layer_range=None,
      expand_nested=False,
      show_layer_activations=True,
      show_trainable=True
  )
  print(f"✓ Model architecture saved as: {img_path}")

except ImportError:
    print("❌ graphviz/pydot not available. Using alternative visualization...")

es = EarlyStopping(monitor='val_loss', patience=12, restore_best_weights=True, verbose=2)
rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=6, min_lr=1e-6, verbose=2)
mc = ModelCheckpoint(m_label + 'lstm_best.keras', monitor='val_loss', save_best_only=True, verbose=2)
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae',tf.keras.metrics.RootMeanSquaredError(),'mape','msle'])
r = model.fit(
  X_train, y_train,
  validation_data=(X_val, y_val),
  epochs=100,
  #batch_size=512,
  callbacks=[es, rlr, mc ],
  verbose=1

)

plt.title("Loss on data")
plt.plot(r.history['loss'], label="loss")
plt.plot(r.history['val_loss'], label="val_loss")
plt.legend()
plt.show()

plt.title("MAE on data")
plt.plot(r.history['mae'], label="mae")
plt.plot(r.history['val_mae'], label="val_mae")
plt.legend()
plt.show()

plt.title("mape on data")
plt.plot(r.history['mape'], label="mape")
plt.plot(r.history['val_mape'], label="val_mape")
plt.legend()
plt.show()

plt.title("msle on data")
plt.plot(r.history['msle'], label="msle")
plt.plot(r.history['val_msle'], label="val_msle")
plt.legend()
plt.show()

plt.title("root_mean_squared_error on data")
plt.plot(r.history['root_mean_squared_error'], label="root_mean_squared_error")
plt.plot(r.history['val_root_mean_squared_error'], label="val_root_mean_squared_error")
plt.legend()
plt.show()

best_model = load_model(m_label + 'lstm_best.keras')
y_pred = best_model.predict(X_test)
print("R^2 value for ", m_label)
print(r2_score(y_test.reshape((len(y_test),1)), y_pred.reshape((len(y_pred),1))))

y_pred = best_model.predict(X1)
print("R^2 value for test ", m_label)
print(r2_score(y1.reshape((len(y1),1)), y_pred.reshape((len(y_pred),1))))

plt.figure(figsize=(12, 6))
plt.plot(y_test[-1:, -1], label='Actual Close Price', color='blue')
plt.plot(y_pred[-1:, -1], label='Predicted Close Price', color='red', linestyle='--')
plt.title('Actual vs. Predicted Close Price')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.savefig('actual_vs_predicted.png')
plt.show()



plt.figure(figsize=(12, 6))
plt.plot(y1[-1:, -1], label='Actual Close Price', color='blue')
plt.plot(y_pred[-1:, -1], label='Predicted Close Price', color='red', linestyle='--')
plt.title('Actual vs. Predicted Close Price Test')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.savefig('actual_vs_predicted.png')
plt.show()



Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 240, 4)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 240, 400)       │       328,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 240, 400)       │       961,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 240, 400)       │       961,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_3 (Bidirectional) │ (None, 400)            │       961,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 150)            │        60,150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 150)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           151 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,273,101 (12.49 MB)

 Trainable params: 3,273,101 (12.49 MB)

 Non-trainable params: 0 (0.00 B)

✓ Model architecture saved as: model_architecture.png
Epoch 1/100
2183/2183 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.0336 - mae: 0.1104 - mape: 9.0090 - msle: 0.0076 - root_mean_squared_error: 0.1622
Epoch 1: val_loss improved from inf to 0.00006, saving model to GeneratedEURUSD lstm_best.keras
2183/2183 ━━━━━━━━━━━━━━━━━━━━ 347s 155ms/step - loss: 0.0336 - mae: 0.1104 - mape: 9.0081 - msle: 0.0076 - root_mean_squared_error: 0.1622 - val_loss: 6.4164e-05 - val_mae: 0.0065 - val_mape: 0.5984 - val_msle: 1.4840e-05 - val_root_mean_squared_error: 0.0080 - learning_rate: 0.0010
Epoch 2/100
2183/2183 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 0.0064 - mae: 0.0632 - mape: 5.1302 - msle: 0.0013 - root_mean_squared_error: 0.0800
Epoch 2: val_loss did not improve from 0.00006
2183/2183 ━━━━━━━━━━━━━━━━━━━━ 301s 138ms/step - loss: 0.0064 - mae: 0.0632 - mape: 5.1300 - msle: 0.0013 - root_mean_squared_error: 0.0800 - val_loss: 4.2718e-04 - val_mae: 0.0188 - val_mape: 1.6696 - val_msle: 9.4010

In [12]:
!zip -r "target.zip" "."

  adding: .config/ (stored 0%)
  adding: .config/active_config (stored 0%)
  adding: .config/.last_update_check.json (deflated 22%)
  adding: .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db (deflated 97%)
  adding: .config/configurations/ (stored 0%)
  adding: .config/configurations/config_default (deflated 15%)
  adding: .config/default_configs.db (deflated 98%)
  adding: .config/logs/ (stored 0%)
  adding: .config/logs/2025.10.02/ (stored 0%)
  adding: .config/logs/2025.10.02/13.35.57.498101.log (deflated 86%)
  adding: .config/logs/2025.10.02/13.35.08.924114.log (deflated 92%)
  adding: .config/logs/2025.10.02/13.36.12.428243.log (deflated 56%)
  adding: .config/logs/2025.10.02/13.35.48.839372.log (deflated 58%)
  adding: .config/logs/2025.10.02/13.36.11.709641.log (deflated 57%)
  adding: .config/logs/2025.10.02/13.36.03.080584.log (deflated 58%)
  adding: .config/.last_opt_in_prompt.yaml (stored 0%)
  adding: .config/config_sentinel (stored 0%)
  adding: .co

In [13]:
"""
best_model = load_model(m_label + 'lstm_best.keras')
    y_pred = best_model.predict(X_test)
    print("R^2 value for ", m_label)
    print(r2_score(y_test.reshape((len(y_test),1)), y_pred.reshape((len(y_pred),1))))

    plt.figure(figsize=(12, 6))
    plt.plot(y_test[:, -1], label='Actual Close Price', color='blue')
    plt.plot(y_pred[:, -1], label='Predicted Close Price', color='red', linestyle='--')
    plt.title('Actual vs. Predicted Close Price')
    plt.xlabel('Time')
    plt.ylabel('Close Price')
    plt.legend()
    plt.grid(True)
    plt.savefig('actual_vs_predicted.png')
    plt.show()

    y_pred = best_model.predict(X1)
    print("R^2 value for test ", m_label)
    print(r2_score(y1.reshape((len(y1),1)), y_pred.reshape((len(y_pred),1))))

    plt.figure(figsize=(12, 6))
    plt.plot(y1[:, -1], label='Actual Close Price', color='blue')
    plt.plot(y_pred[:, -1], label='Predicted Close Price', color='red', linestyle='--')
    plt.title('Actual vs. Predicted Close Price Test')
    plt.xlabel('Time')
    plt.ylabel('Close Price')
    plt.legend()
    plt.grid(True)
    plt.savefig('actual_vs_predicted.png')
    plt.show()
"""

'\nbest_model = load_model(m_label + \'lstm_best.keras\')\n    y_pred = best_model.predict(X_test)\n    print("R^2 value for ", m_label)\n    print(r2_score(y_test.reshape((len(y_test),1)), y_pred.reshape((len(y_pred),1))))\n\n    plt.figure(figsize=(12, 6))\n    plt.plot(y_test[:, -1], label=\'Actual Close Price\', color=\'blue\')\n    plt.plot(y_pred[:, -1], label=\'Predicted Close Price\', color=\'red\', linestyle=\'--\')\n    plt.title(\'Actual vs. Predicted Close Price\')\n    plt.xlabel(\'Time\')\n    plt.ylabel(\'Close Price\')\n    plt.legend()\n    plt.grid(True)\n    plt.savefig(\'actual_vs_predicted.png\')\n    plt.show()\n\n    y_pred = best_model.predict(X1)\n    print("R^2 value for test ", m_label)\n    print(r2_score(y1.reshape((len(y1),1)), y_pred.reshape((len(y_pred),1))))\n\n    plt.figure(figsize=(12, 6))\n    plt.plot(y1[:, -1], label=\'Actual Close Price\', color=\'blue\')\n    plt.plot(y_pred[:, -1], label=\'Predicted Close Price\', color=\'red\', linestyle=\'--\

In [14]:
dir_contents = os.listdir(".")
t_symbol = joblib.load("symbol.joblib")
# Filter the list to include only files, not directories
# os.path.join is used to create a full path for isfile() to check
files = [item for item in dir_contents]

file_target = []

for filename in files:
    for t_s in t_symbol:
        if t_s in filename and "lstm_best.keras" in filename:
            print(filename)
            #file_target.append(filename)
print("----------------------------------------------------")

print(len(file_target))


----------------------------------------------------
0


In [15]:


best_model = load_model(file_target[0])

IndexError: list index out of range

In [ ]:
y_pred = best_model.predict(X_test)
print(y_pred)

In [ ]:
print(y_test)

In [ ]:

r2_score(y_test.reshape((len(y_test),1)), y_pred.reshape((len(y_pred),1)))

In [ ]:
plt.figure(figsize=(12, 6))
plt.plot(y_test[:, -1], label='Actual Close Price', color='blue')
plt.plot(y_pred[:, -1], label='Predicted Close Price', color='red', linestyle='--')
plt.title('Actual vs. Predicted Close Price')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.savefig('actual_vs_predicted.png')
plt.show()

In [ ]:
# Save this as plot_forecast.py and run where your model, x_test, y_test (and optional scalers) are available.

import numpy as np
import matplotlib.pyplot as plt

def ensure_2d_preds(preds):
    """Normalize model.predict outputs to shape (n_samples, n_features)."""
    preds = np.asarray(preds)
    if preds.ndim == 3:
        # common case: (n_samples, 1, n_features) or (n_samples, seq_len, n_features)
        # we assume model outputs final-step predictions if seq_len>1
        if preds.shape[1] == 1:
            preds = preds[:, 0, :]
        else:
            preds = preds[:, -1, :]
    elif preds.ndim == 1:
        preds = preds.reshape(-1, 1)
    return preds

def plot_test_vs_pred_close(y_test, preds, output_index=-1, figsize=(12,5), savepath=None):
    """
    Plot actual vs predicted for the 'close' column (default last column).
    y_test: (n, n_features)
    preds: (n, n_features)
    """
    y_test = np.asarray(y_test)
    preds = np.asarray(preds)
    # normalize shapes
    preds = ensure_2d_preds(preds)

    actual_close = y_test[:, output_index]
    pred_close   = preds[:, output_index]

    plt.figure(figsize=figsize)
    plt.plot(actual_close, label='Actual Close')
    plt.plot(pred_close, label='Predicted Close')
    plt.xlabel('Time (test index)')
    plt.ylabel('Close price')
    plt.title('Actual vs Predicted Close Price (test set)')
    plt.legend()
    plt.grid(True)
    if savepath:
        plt.savefig(savepath, bbox_inches='tight')
    plt.show()

def recursive_forecast(model, last_window, n_steps=200):
    """
    Do recursive multi-step forecasting:
      - model.predict expects input shape (1, window_len, n_features)
      - last_window: shape (window_len, n_features)
      - returns array shape (n_steps, n_features)
    """
    last_window = last_window.reshape((len(last_window),1))
    if last_window.ndim != 2:
        raise ValueError("last_window must be 2D: (window_len, n_features)")

    window_len, n_features = last_window.shape
    history = last_window.copy()
    preds = []
    for i in range(n_steps):
        x_in = history.reshape(1, window_len, n_features)
        p = model.predict(x_in)
        p = ensure_2d_preds(p)[0]  # shape: (n_features,)
        preds.append(p)
        # slide window
        history = np.vstack([history[1:], p.reshape(1, n_features)])
    return np.vstack(preds)  # shape (n_steps, n_features)

def plot_extended_series(y_test, future_preds, output_index=-1, figsize=(14,5), savepath=None):
    """
    Plot the test-close series and appended future predictions as one continuous line.
    """
    actual_close = np.asarray(y_test)[:, output_index]
    future_close = np.asarray(future_preds)[:, output_index]
    combined = np.concatenate([actual_close, future_close])

    plt.figure(figsize=figsize)
    plt.plot(combined, label='Actual (test) + Forecast (future)')
    # mark border between known and forecast
    split_index = len(actual_close)
    plt.axvline(split_index - 0.5, linestyle='--', linewidth=1)
    plt.text(split_index + 5, combined[split_index], ' Forecast starts', va='center')
    plt.xlabel('Time (index)')
    plt.ylabel('Close price')
    plt.title(f'Actual Close (test) and {len(future_close)} Step Forecast')
    plt.legend()
    plt.grid(True)
    if savepath:
        plt.savefig(savepath, bbox_inches='tight')
    plt.show()



In [ ]:
# ------------------------------------------------------------
# USAGE (example)
# ------------------------------------------------------------
# Assumptions:
# - x_test shape = (n_samples, window_len, n_features) e.g. (6247, 48, 4)
# - y_test shape = (n_samples, n_features) e.g. (6247, 4)
# - model.predict(x_test) -> (n_samples, n_features) (or shape convertible)
#
# Optional:
# - scaler_X (used during training on inputs) or scaler_y (used on outputs).
#   If present, inverse_transform predictions and y_test before plotting.
#
# Replace these names with your actual variables present in the workspace.

# Example (uncomment and run where variables exist):
preds_test = best_model.predict(X_test)
preds_test = ensure_2d_preds(preds_test)

# # 1) plot actual vs predicted (test)
plot_test_vs_pred_close(y_test, preds_test, output_index=-1, savepath='test_vs_pred.png')


In [ ]:
#
# # 2) recursive forecast next 2000 values starting from last input window:
last_window = X_test[-1].reshape((len(X_test[-1]),1))   # shape (window_len, n_features)
future_preds = recursive_forecast(best_model, last_window, n_steps=200)
future_preds_inv = future_preds

# # 3) plot extended series (append future close to test close)
plot_extended_series(y_test, future_preds_inv, output_index=-1, savepath='extended_forecast.png')
#
# # Optional: save future_preds_inv to disk
# # np.save('future_preds.npy', future_preds_inv)