<a href="https://colab.research.google.com/github/dbright123/Dbot-Advance/blob/main/lstm_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import MetaTrader5 as mt5
import numpy as np
import pandas as pd





In [5]:
print("MetaTrader5 package author: ",mt5.__author__)
print("MetaTrader5 package version: ",mt5.__version__)

trade_active = mt5.initialize()

print(trade_active)

if not trade_active:
    print('Initialization failed, check internet connection. You must have Meta Trader 5 installed.')
    mt5.shutdown()

else:
    print(mt5.account_info()._asdict())
    print("\n")
    print(mt5.terminal_info()._asdict())
    print("\n")
    print(mt5.symbols_total())

MetaTrader5 package author:  MetaQuotes Ltd.
MetaTrader5 package version:  5.0.4200
True
{'login': 213644473, 'trade_mode': 0, 'leverage': 1000, 'limit_orders': 500, 'margin_so_mode': 0, 'trade_allowed': True, 'trade_expert': True, 'margin_mode': 2, 'currency_digits': 2, 'fifo_close': False, 'balance': 200.0, 'credit': 0.0, 'profit': 0.0, 'equity': 200.0, 'margin': 0.0, 'margin_free': 200.0, 'margin_level': 0.0, 'margin_so_call': 25.0, 'margin_so_so': 15.0, 'margin_initial': 0.0, 'margin_maintenance': 0.0, 'assets': 0.0, 'liabilities': 0.0, 'commission_blocked': 0.0, 'name': 'micheal bright omage ', 'server': 'OctaFX-Demo', 'currency': 'USD', 'company': 'Octa Markets Incorporated'}


{'community_account': False, 'community_connection': False, 'connected': True, 'dlls_allowed': False, 'trade_allowed': False, 'tradeapi_disabled': False, 'email_enabled': False, 'ftp_enabled': False, 'notifications_enabled': False, 'mqid': False, 'build': 5328, 'maxbars': 100000, 'codepage': 0, 'ping_last'

In [6]:
account = mt5.account_info()
terminal = mt5.terminal_info()

print(account.equity)

if(terminal.connected == True or terminal.trade_allowed == True):
    print("AI is successfully functional")
else:
    print("Please make sure metatrade 5 has internet and algo Trade is Turn On")

200.0
AI is successfully functional


In [7]:
symbols = mt5.symbols_get()
print(len(symbols))
t_symbol = []
for symbol in symbols:
    if "USD" in symbol.name:
        print("Yes ", symbol.name)
        t_symbol.append(symbol.name)

print(len(t_symbol))

280
Yes  EURUSD
Yes  GBPUSD
Yes  USDJPY
Yes  USDCHF
Yes  AUDUSD
Yes  NZDUSD
Yes  USDCAD
Yes  USDMXN
Yes  USDZAR
Yes  XAGUSD
Yes  XAUUSD
Yes  XBRUSD
Yes  XTIUSD
Yes  XNGUSD
Yes  BTCUSD
Yes  ETHUSD
Yes  LTCUSD
Yes  XRPUSD
Yes  BCHUSD
Yes  AAVEUSD
Yes  ADAUSD
Yes  ALGOUSD
Yes  ATOMUSD
Yes  AVAXUSD
Yes  AXSUSD
Yes  BNBUSD
Yes  DASHUSD
Yes  DOGEUSD
Yes  DOTUSD
Yes  FILUSD
Yes  GRTUSD
Yes  ICPUSD
Yes  IOTAUSD
Yes  LINKUSD
Yes  LRCUSD
Yes  MANAUSD
Yes  NEARUSD
Yes  SOLUSD
Yes  UNIUSD
Yes  ZECUSD
Yes  ETCUSD
Yes  TRXUSD
Yes  FETUSD
Yes  ARBUSD
Yes  APTUSD
Yes  SUIUSD
Yes  USDDKK
Yes  USDCZK
Yes  USDHUF
Yes  USDNOK
Yes  USDPLN
Yes  USDSEK
Yes  USDSGD
Yes  USDHKD
Yes  USDCNH
Yes  USDTRY
Yes  XBRUSD.Daily
Yes  XTIUSD.Daily
Yes  BTCUSD.Daily
Yes  ETHUSD.Daily
Yes  XRPUSD.Daily
Yes  LTCUSD.Daily
Yes  BCHUSD.Daily
Yes  LINKUSD.Daily
Yes  SOLUSD.Daily
65


In [12]:
market = mt5.copy_rates_from_pos(t_symbol[10], mt5.TIMEFRAME_M30, 0, 99999)
display(market)
print(market.shape)
print(t_symbol[10])
t_s = t_symbol[10]

data = []
for i in range(len(market)):
    data.append([market[i][1],market[i][2],market[i][3],market[i][4]])
df = pd.DataFrame(data, columns=["open", "high","low", "close"])
df.to_csv("Generated"+t_s+" dbot.csv", index=False)


array([(1492021800, 1275.06, 1276.56, 1273.81, 1273.81,  6823, 10, 0),
       (1492023600, 1273.86, 1274.58, 1272.98, 1273.66,  6259, 11, 0),
       (1492025400, 1273.66, 1275.64, 1273.56, 1275.64,  5513, 14, 0),
       ...,
       (1760135400, 4005.32, 4021.4 , 4005.25, 4011.15, 25364, 26, 0),
       (1760137200, 4011.12, 4015.53, 4005.65, 4012.26,  7374, 26, 0),
       (1760139000, 4012.3 , 4020.55, 4007.56, 4018.12,  6617, 26, 0)],
      dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

(99999,)
XAUUSD


In [5]:
test_symbol = []
for t_s in t_symbol:
    market = mt5.copy_rates_from_pos(t_s, mt5.TIMEFRAME_H1, 0, 99999)
    if(len(market) > 80000 ):
        data = []
        for i in range(len(market)):
            data.append([market[i][1],market[i][2],market[i][3],market[i][4]])
        df = pd.DataFrame(data, columns=["open", "high","low", "close"])
        df.to_csv("Generated"+t_s+" dbot.csv", index=False)
        test_symbol.append(t_s)


In [6]:

for t_s in test_symbol:
    market = mt5.copy_rates_from_pos(t_s, mt5.TIMEFRAME_D1, 0, 1000)
    if(len(market) > 900):
        data = []
        for i in range(len(market)):
            data.append([market[i][1],market[i][2],market[i][3],market[i][4]])
        df = pd.DataFrame(data, columns=["open", "high","low", "close"])
        df.to_csv("Generated"+t_s+" test.csv", index=False)



In [7]:
import joblib

joblib.dump(t_symbol,"symbol.joblib")

['symbol.joblib']

In [13]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
print(tf.__version__)


2.10.1


In [14]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
import joblib
import os
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import MinMaxScaler



In [15]:
from tensorflow.keras.optimizers import SGD,Adam
import matplotlib.pyplot as plt



from tensorflow.keras import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, BatchNormalization, LayerNormalization, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

from sklearn.metrics import r2_score
from tensorflow.keras.models import load_model
import keras

In [16]:
# Get the list of all files and directories in the specified path

dir_contents = os.listdir(".")
t_symbol = joblib.load("symbol.joblib")

In [17]:
print(t_symbol)

['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD', 'NZDUSD', 'USDCAD', 'USDMXN', 'USDZAR', 'XAGUSD', 'XAUUSD', 'XBRUSD', 'XTIUSD', 'XNGUSD', 'BTCUSD', 'ETHUSD', 'LTCUSD', 'XRPUSD', 'BCHUSD', 'AAVEUSD', 'ADAUSD', 'ALGOUSD', 'ATOMUSD', 'AVAXUSD', 'AXSUSD', 'BNBUSD', 'DASHUSD', 'DOGEUSD', 'DOTUSD', 'FILUSD', 'GRTUSD', 'ICPUSD', 'IOTAUSD', 'LINKUSD', 'LRCUSD', 'MANAUSD', 'NEARUSD', 'SOLUSD', 'UNIUSD', 'ZECUSD', 'ETCUSD', 'TRXUSD', 'FETUSD', 'ARBUSD', 'APTUSD', 'SUIUSD', 'USDDKK', 'USDCZK', 'USDHUF', 'USDNOK', 'USDPLN', 'USDSEK', 'USDSGD', 'USDHKD', 'USDCNH', 'USDTRY', 'XBRUSD.Daily', 'XTIUSD.Daily', 'BTCUSD.Daily', 'ETHUSD.Daily', 'XRPUSD.Daily', 'LTCUSD.Daily', 'BCHUSD.Daily', 'LINKUSD.Daily', 'SOLUSD.Daily']


In [6]:
#t_symbol = ["EURUSD","AUDUSD","GBPUSD","USDCAD"]

In [19]:

# Filter the list to include only files, not directories
# os.path.join is used to create a full path for isfile() to check
files = [item for item in dir_contents]

file_target = []
test_target = []

for filename in files:
    for t_s in t_symbol:
        if t_s in filename  and "dbot.csv" in filename:
            print(filename)
            file_target.append(filename)
            test_target.append(filename.replace("dbot","test"))

print("----------------------------------------------------")

print(len(file_target))
print(len(test_target))
train_dfs = []
for f_t in file_target:
    train_dfs.append(pd.read_csv(f_t))
try:
    train_dfs_test = []
    for f_t in test_target:
        train_dfs_test.append(pd.read_csv(f_t))
except:
    pass

GeneratedAUDUSD dbot.csv
GeneratedEURUSD dbot.csv
GeneratedGBPUSD dbot.csv
GeneratedNZDUSD dbot.csv
GeneratedUSDCAD dbot.csv
GeneratedUSDCHF dbot.csv
GeneratedUSDJPY dbot.csv
GeneratedUSDMXN dbot.csv
GeneratedUSDZAR dbot.csv
GeneratedXAUUSD dbot.csv
----------------------------------------------------
10
10


In [ ]:
display(train_dfs[0])

In [ ]:
display(train_dfs_test[0])

In [ ]:
print(train_dfs[0].values[:,-1:])

In [20]:
def create_sequences(data_scaled, seq_len, pred_steps = 5):
    """
    data_scaled: np.array shaped (n_rows, n_features)
    returns X (n_samples, seq_len, n_features), y (n_samples, n_features)
    where y is the row immediately following the window.
    """
    X, y = [], []
    n_rows = data_scaled.shape[0]
    for i in range(n_rows - seq_len - pred_steps + 1):
        X.append(data_scaled[i:i+seq_len])
        y.append(data_scaled[i+seq_len : i + seq_len+pred_steps, -1])
    X = np.array(X)
    y = np.array(y)
    return X, y





In [21]:
n = 9

In [22]:

def preprocess_and_save_scalers(data_x, data_y, scaler_x_filename='scaler_x.joblib', scaler_y_filename='scaler_y.joblib'):
    """
    Preprocesses 3D X and 2D Y data, scales them to a range of [0, 1],
    and saves the fitted scalers.

    Args:
        data_x (np.ndarray): The input features, a 3D numpy array of shape (samples, timesteps, features).
        data_y (np.ndarray): The target values, a 2D numpy array of shape (samples, output_dim).
        scaler_x_filename (str): Filename to save the scaler for X data.
        scaler_y_filename (str): Filename to save the scaler for Y data.

    Returns:
        tuple: A tuple containing the scaled X data (3D) and scaled Y data (2D).
    """
    try:
        # --- Preprocess X data (3D) ---
        # Reshape 3D data to 2D for scaler
        original_shape_x = data_x.shape
        data_x_reshaped = data_x.reshape(-1, original_shape_x[2])

        # Initialize and fit the scaler for X
        scaler_x = MinMaxScaler(feature_range=(0, 1))
        scaled_x_reshaped = scaler_x.fit_transform(data_x_reshaped)

        # Reshape the scaled data back to its original 3D shape
        scaled_x = scaled_x_reshaped.reshape(original_shape_x)

        # --- Preprocess Y data (2D) ---
        scaler_y = MinMaxScaler(feature_range=(0, 1))
        scaled_y = scaler_y.fit_transform(data_y)

        # --- Save the scalers ---
        joblib.dump(scaler_x, scaler_x_filename)
        joblib.dump(scaler_y, scaler_y_filename)
        print(f"Scaler for X saved to '{scaler_x_filename}'")
        print(f"Scaler for Y saved to '{scaler_y_filename}'")

        return scaled_x, scaled_y

    except Exception as e:
        print(f"An error occurred during preprocessing: {e}")
        return None, None

def transform_data(data_x=None, data_y=None, scaler_x_filename='scaler_x.joblib', scaler_y_filename='scaler_y.joblib'):
    """
    Transforms new 3D X and/or 2D Y data using saved scalers.

    Args:
        data_x (np.ndarray, optional): The new input features (3D numpy array). Defaults to None.
        data_y (np.ndarray, optional): The new target values (2D numpy array). Defaults to None.
        scaler_x_filename (str): Filename of the saved scaler for X data.
        scaler_y_filename (str): Filename of the saved scaler for Y data.

    Returns:
        tuple: A tuple containing (scaled_x, scaled_y). Elements will be None if not provided.
    """
    scaled_x = None
    scaled_y = None

    # Transform X data if provided
    if data_x is not None:
        if not os.path.exists(scaler_x_filename):
            print(f"Error: Scaler file for X not found at '{scaler_x_filename}'")
        else:
            try:
                scaler_x = joblib.load(scaler_x_filename)
                original_shape_x = data_x.shape
                # Ensure there's data to reshape
                if original_shape_x[0] > 0:
                    data_x_reshaped = data_x.reshape(-1, original_shape_x[2])
                    scaled_x_reshaped = scaler_x.transform(data_x_reshaped)
                    scaled_x = scaled_x_reshaped.reshape(original_shape_x)
                else:
                    # Handle empty array case
                    scaled_x = np.array([]).reshape(original_shape_x)
            except Exception as e:
                print(f"An error occurred during X transformation: {e}")

    # Transform Y data if provided
    if data_y is not None:
        if not os.path.exists(scaler_y_filename):
            print(f"Error: Scaler file for Y not found at '{scaler_y_filename}'")
        else:
            try:
                scaler_y = joblib.load(scaler_y_filename)
                scaled_y = scaler_y.transform(data_y)
            except Exception as e:
                print(f"An error occurred during Y transformation: {e}")

    return scaled_x, scaled_y


def inverse_transform_data(scaled_x=None, scaled_y=None, scaler_x_filename='scaler_x.joblib', scaler_y_filename='scaler_y.joblib'):
    """
    Inverse transforms scaled 3D X and/or 2D Y data to their original scale.

    Args:
        scaled_x (np.ndarray, optional): The scaled input features (3D numpy array). Defaults to None.
        scaled_y (np.ndarray, optional): The scaled target values or predictions (2D numpy array). Defaults to None.
        scaler_x_filename (str): Filename of the saved scaler for X data.
        scaler_y_filename (str): Filename of the saved scaler for Y data.

    Returns:
        tuple: A tuple containing (inversed_x, inversed_y). Elements will be None if not provided.
    """
    inversed_x = None
    inversed_y = None

    # Inverse transform X data if provided
    if scaled_x is not None:
        if not os.path.exists(scaler_x_filename):
            print(f"Error: Scaler file for X not found at '{scaler_x_filename}'")
        else:
            try:
                scaler_x = joblib.load(scaler_x_filename)
                original_shape_x = scaled_x.shape
                # Ensure there's data to reshape
                if original_shape_x[0] > 0:
                    scaled_x_reshaped = scaled_x.reshape(-1, original_shape_x[2])
                    inversed_x_reshaped = scaler_x.inverse_transform(scaled_x_reshaped)
                    inversed_x = inversed_x_reshaped.reshape(original_shape_x)
                else:
                    inversed_x = np.array([]).reshape(original_shape_x)
            except Exception as e:
                print(f"An error occurred during X inverse transformation: {e}")

    # Inverse transform Y data if provided
    if scaled_y is not None:
        if not os.path.exists(scaler_y_filename):
            print(f"Error: Scaler file for Y not found at '{scaler_y_filename}'")
        else:
            try:
                scaler_y = joblib.load(scaler_y_filename)
                inversed_y = scaler_y.inverse_transform(scaled_y)
            except Exception as e:
                print(f"An error occurred during Y inverse transformation: {e}")

    return inversed_x, inversed_y


In [24]:
m_label = file_target[n].replace("dbot.csv","")
train_df = train_dfs[n]
#train_df_test = train_dfs_test[n]
print(m_label)
SEQ_LEN = 240 # length of input sequence (timesteps). Typical choices: 30, 60, 90
n_rows, n_features = train_df.values.shape

X, y = create_sequences(train_df.values, SEQ_LEN, 5)  # X: (n_samples, SEQ_LEN, n_features), y: (n_samples, n_features)
#X1, y1 = create_sequences(train_df.values, SEQ_LEN, 5)  # X: (n_samples, SEQ_LEN, n_features), y: (n_samples, n_features)

n_samples = X.shape[0]


GeneratedXAUUSD 


In [25]:
X, y = preprocess_and_save_scalers(X, y)
#X1, y1 = transform_data(X1, y1)

Scaler for X saved to 'scaler_x.joblib'
Scaler for Y saved to 'scaler_y.joblib'


In [26]:
print(X[-1])

[[0.93920424 0.94167024 0.9378356  0.93973666]
 [0.93987521 0.94003777 0.935723   0.93863335]
 [0.93862319 0.93852289 0.93782869 0.93879591]
 [0.93884454 0.94115145 0.93835425 0.94158703]
 [0.94164949 0.94206452 0.94182223 0.942175  ]
 [0.94219595 0.94135551 0.94062935 0.93986809]
 [0.93987867 0.93960544 0.9406501  0.94020703]
 [0.94020378 0.94008965 0.94072617 0.94021049]
 [0.9402107  0.93999626 0.93923939 0.93961907]
 [0.93965386 0.93981987 0.94043919 0.94044222]
 [0.94045972 0.94119987 0.94191559 0.94102673]
 [0.94104423 0.94100618 0.94170121 0.94125154]
 [0.94125175 0.94118949 0.94202623 0.94088839]
 [0.94084709 0.94050122 0.94171504 0.94045951]
 [0.94045626 0.9404528  0.94144189 0.94118583]
 [0.94162528 0.94283234 0.94183952 0.94372447]
 [0.943697   0.94513924 0.94396595 0.94583078]
 [0.94582405 0.95203229 0.94686689 0.94947965]
 [0.94947636 0.94901637 0.95007209 0.9491407 ]
 [0.9491305  0.94837306 0.94700865 0.94667815]
 [0.94673367 0.94724901 0.94731983 0.9459795 ]
 [0.94597623 

In [27]:
print(y[-1])

[0.98010244 0.9823056  0.98431161 0.98469552 0.98672228]


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0, shuffle=False)
X_val, X_test, y_val,  y_test = train_test_split(X_test, y_test, test_size=0.01, random_state=0, shuffle=False)

seq_len = X_train.shape[1]
n_features = X_train.shape[2]
output_dim = y_train.shape[1]

i = Input(shape=(seq_len, n_features))
X = Bidirectional(LSTM(100, return_sequences=True))(i)
X = Bidirectional(LSTM(100, return_sequences=True))(X)
X = Bidirectional(LSTM(100, return_sequences=True))(X)
X = Bidirectional(LSTM(100))(X)
#X = Dropout(0.5)(X)
X = Dense(150, activation="relu")(X)
X = Dropout(0.5)(X)
X = Dense(output_dim)(X)

model = Model(i, X)
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 240, 4)]          0         
                                                                 
 bidirectional (Bidirectiona  (None, 240, 200)         84000     
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 240, 200)         240800    
 nal)                                                            
                                                                 
 bidirectional_2 (Bidirectio  (None, 240, 200)         240800    
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 200)              240800    
 nal)                                                        

In [29]:

es = EarlyStopping(monitor='val_loss', patience=12, restore_best_weights=True, verbose=2)
rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=6, min_lr=1e-6, verbose=2)
mc = ModelCheckpoint(m_label + 'lstm_best.keras', monitor='val_loss', save_best_only=True, verbose=2)
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae',tf.keras.metrics.RootMeanSquaredError(),'mape','msle'])
r = model.fit(
  X_train, y_train,
  validation_data=(X_val, y_val),
  epochs=100,
  #batch_size=1024,
  callbacks=[es, rlr, mc ],
  verbose=1

)




Epoch 1/100


In [ ]:
plt.title("Loss on data")
plt.plot(r.history['loss'], label="loss")
plt.plot(r.history['val_loss'], label="val_loss")
plt.legend()
plt.show()

plt.title("MAE on data")
plt.plot(r.history['mae'], label="mae")
plt.plot(r.history['val_mae'], label="val_mae")
plt.legend()
plt.show()

plt.title("mape on data")
plt.plot(r.history['mape'], label="mape")
plt.plot(r.history['val_mape'], label="val_mape")
plt.legend()
plt.show()

plt.title("msle on data")
plt.plot(r.history['msle'], label="msle")
plt.plot(r.history['val_msle'], label="val_msle")
plt.legend()
plt.show()

plt.title("root_mean_squared_error on data")
plt.plot(r.history['root_mean_squared_error'], label="root_mean_squared_error")
plt.plot(r.history['val_root_mean_squared_error'], label="val_root_mean_squared_error")
plt.legend()
plt.show()




In [1]:
best_model = load_model(m_label + 'lstm_best.keras')


NameError: name 'load_model' is not defined

In [ ]:
best_model.summary()

In [ ]:
best_model.evaluate(X1[-100:],y1[-100:])

In [ ]:
y_pred = best_model.predict(X[-100:])

In [ ]:
print(y[-2:], " comparing to ", y_pred[-2:])

In [ ]:
print("R^2 value for ", m_label)
print(r2_score(y[-100:], y_pred))

In [ ]:
y_pred = best_model.predict(X1)
print("R^2 value for test ", m_label)
print(r2_score(y1, y_pred))

In [ ]:
print(y1[-1], " comparing to ", y_pred[-1])

In [ ]:




plt.figure(figsize=(12, 6))
plt.plot(y_test[:, 0], label='Actual Close Price', color='blue')
plt.plot(y_pred[:, 0], label='Predicted Close Price', color='red', linestyle='--')
plt.title('Actual vs. Predicted Close Price')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.savefig('actual_vs_predicted.png')
plt.show()



plt.figure(figsize=(12, 6))
plt.plot(y1[:, 0], label='Actual Close Price', color='blue')
plt.plot(y_pred[:, 0], label='Predicted Close Price', color='red', linestyle='--')
plt.title('Actual vs. Predicted Close Price Test')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.savefig('actual_vs_predicted.png')
plt.show()